function MeasurementinNISTshop = importMeta(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  MEASUREMENTINNISTSHOP = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  MEASUREMENTINNISTSHOP = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  MEASUREMENTINNISTSHOP = IMPORTFILE(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  MeasurementinNISTshop = importfile("D:\meas\TIGWelding2023\Measurement in NIST shop.xlsx", "data_catalog", [5, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Dec-2024 12:05:45

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [5, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 20);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["WeldType", "Number", "Run", "BaseMetal", "BaseMetalThickness", "GasUsed", "PowerAndIgnitionOption", "HF", "Current", "Pulser", "BackgroundA", "PPS", "PeakTime", "Fc", "AntennaGain", "CableLoss", "Distance", "Directory", "FileName", "Notes"];
opts.VariableTypes = ["categorical", "double", "double", "categorical", "double", "categorical", "categorical", "categorical", "double", "categorical", "categorical", "categorical", "categorical", "double", "double", "double", "double", "string", "string", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["Directory", "FileName"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["WeldType", "BaseMetal", "GasUsed", "PowerAndIgnitionOption", "HF", "Pulser", "BackgroundA", "PPS", "PeakTime", "Directory", "FileName", "Notes"], "EmptyFieldRule", "auto");

% Import the data
MeasurementinNISTshop = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    MeasurementinNISTshop = [MeasurementinNISTshop; tb]; %#ok<AGROW>
end

end