function Hd = mr_filter_design(M,N)
%MRFILTERDESIGN Returns a discrete-time filter object.
%
% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 20-Mar-2024 21:33:04
%
% Equiripple FIR Lowpass filter designed using the FIRPM function.
%
% All frequency values are in Hz.
%
% Author: Rick Candell
% Organization: National Institute of Standards and Technology
% Email: rick.candell@nist.gov

Fs = 1; % Sampling Frequency

Fpass = 0.8*(Fs/2)*M/N;  % Passband Frequency
Fstop = 0.99*(Fs/2)*M/N; % Stopband Frequency
Dpass = 0.01;            % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 16;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop], [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

end